### ISSUE TITLE
Indian Numbering System conversion

### ISSUE THREAD

**Issue by MohsenAlyafei** [NARUDESIGNS/numToWords#1]
With regards to conversion in general, could you please assist on this: https://stackoverflow.com/questions/62795243/indian-numbering-system-how-to-convert-into-the-official-and-common-use-numberi
Thanks

**Comment by NARUDESIGNS** [comment]
Hi, I saw ur post on stackoverflow through this link u sent and I was a
little confused tho I understood a little about the lakh (if I spelt that
correctly) numbering system.

My emails gets too many unnecessary emails so I can hardly filter messages
like urs, you can reach me on Twitter https://twitter.com/paulister007
where I'm usually available

✌️

**Comment by NARUDESIGNS** [comment]
@MohsenAlyafei send a dm on twitter ✌️
